import org.apache.hadoop.fs.shell.PathExceptions.PathIOException;
public class FunctionUse5899 {
public void funcUse() {
PathIOException pathioexception = new PathIOException();
pathioexception.getTargetPath();
}
}